version: '3'

services:
  asterisk:
    image: opusvl/asterisk:latest
    volumes:
      - "${PWD}/etc/asterisk/:/etc/asterisk:rw"
      - "${PWD}/log/asterisk:/var/log/asterisk"
      - "${PWD}/odbc.ini:/etc/odbc.ini"
      - "${PWD}/odbcinst.ini:/etc/odbcinst.ini"
      - "${PWD}/log/supervisor:/var/log/supervisor"
    network_mode: "host"

  db:
    image: postgres:12
    environment:
      POSTGRES_DB:  "${POSTGRES_DB:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "${PWD}/.pgdata:/var/lib/postgresql/data"
      - "${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    ports:
      - "5432:5432"
    restart: always    
